# .goreleaser.yaml
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy

release:
  footer: |
    **Full Changelog**: https://github.com/mrusme/neonmodem/compare/{{ .PreviousTag }}...{{ .Tag }}

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - netbsd
      - openbsd
      - freebsd
      # - plan9
      # - android
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: riscv64

      - goos: dragonfly
        goarch: 386
      - goos: dragonfly
        goarch: arm
      - goos: dragonfly
        goarch: arm64
      - goos: dragonfly
        goarch: ppc64
      - goos: dragonfly
        goarch: ppc64le
      - goos: dragonfly
        goarch: riscv64

      - goos: freebsd
        goarm: arm64
      - goos: freebsd
        goarm: ppc64
      - goos: freebsd
        goarm: ppc64le
      - goos: freebsd
        goarm: riscv64

      - goos: netbsd
        goarch: arm64
      - goos: netbsd
        goarch: ppc64
      - goos: netbsd
        goarch: ppc64le
      - goos: netbsd
        goarch: riscv64

      - goos: plan9
        goarm: arm64
      - goos: plan9
        goarm: ppc64
      - goos: plan9
        goarm: ppc64le
      - goos: plan9
        goarm: riscv64

      - goos: windows
        goarm: ppc64
      - goos: windows
        goarm: ppc64le
      - goos: windows
        goarm: riscv64


